[tool.poetry]
name = "gdu"
version = "0.1.0"
description = "Dynamic IP publisher to keep Gandi LiveDNS updated"
authors = ["Yago Riveiro <yago.riveiro@gmail.com>"]

license = "MIT"
readme = 'README.md'
repository = "https://github.com/gandi-livedns-updater"
homepage = "https://github.com/yriveiro/gandi-livedns-updater"
keywords = ['Gandi', 'LiveDNS']

classifiers = []

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
requests = "^2.24.0"
tomlkit = "^0.6.0"
halo = "^0.0.29"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.3"
mypy = "^0.782"
pynvim = "^0.4.1"
pre-commit = "^2.5.1"

[tool.poetry.scripts]
gdu = 'src.gdu.cli:gdu'

[tool.isort]
line_length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
